services:
  - type: web
    name: binance-grid-bot
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: API_KEY
        value: your_binance_api_key
      - key: API_SECRET
        value: your_binance_api_secret
      - key: WEBHOOK_PASSPHRASE
        value: "#1960AlGeR@+="
      - key: EXCHANGE_TYPE
        value: spot
      - key: TEST_MODE
        value: true
      - key: PORT
        value: 10000
